"use client";

import { Editor } from "@monaco-editor/react";
import { $ } from "migacss";
import dynamic from "next/dynamic";
import { useState } from "react";
import { AiFillGithub } from "react-icons/ai";
import { BsStars } from "react-icons/bs";
import { RiShareBoxLine } from "react-icons/ri";
import { defaultCode } from "remark-shaku-code-annotate";
import { Button, Column, Row, Text, View } from "../../components/bare";

const CodeSnippetPreview = dynamic(() => import("./SugarHighTokenPreview"), {
  ssr: false,
});

export function SugarHighTokenInspector({ code: _code }: { code?: string }) {
  const [code, setCode] = useState(_code ?? defaultCode["javascript"] ?? "");

  const share = () => {
    const query = "code=" + encodeURIComponent(code);
    const url = location.origin + "/sugar-high-token-inspector?" + query;
    const type = "text/plain";
    const blob = new Blob([url], { type });
    const data = [new ClipboardItem({ [type]: blob })];
    navigator.clipboard.write(data).then(
      () => alert("link copied"),
      () => alert("failed to copy link.")
    );
  };
  return (
    <Column $height={"100vh"} $padding={12} $gap={12}>
      <View>
        <Row $alignItems="center" $justifyContent="space-between" $gap={20}>
          <Text type="headline1">
            Sugar High Token Inspector
            <$.a
              href="https://github.com/JSerZANP/shaku"
              target="_blank"
              $fontSize={20}
              $marginLeft={12}
            >
              <AiFillGithub />
            </$.a>
          </Text>
          <$.a href="/" $textDecoration="none">
            <Text type="headline5" $color="#0e67e4">
              <BsStars />
              Shaku →
            </Text>
          </$.a>
        </Row>
        <Text type="body">
          A tool to inspect the tokens generated by{" "}
          <a href="https://github.com/huozhi/sugar-high">Sugar High</a>. Created
          by <a href="https://twitter.com/JSer_ZANP">JSer</a>.
        </Text>
      </View>

      <Row $gap={20} $flex="1 0 0 " $minHeight={0}>
        <Column $flex="1 0 0" $maxWidth={500}>
          <Row $marginBottom="0.5rem">
            <Button
              onClick={share}
              label="Share with below code"
              icon={<RiShareBoxLine />}
            ></Button>
          </Row>
          <Editor
            language={"javascript"}
            height="100%"
            value={code}
            theme="vs-dark"
            onChange={setCode}
            options={{
              minimap: {
                enabled: false,
              },
              lineNumbers: "off",
            }}
          />
        </Column>
        <CodeSnippetPreview code={code} />
      </Row>
    </Column>
  );
}
